# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import data_pb2 as data__pb2


class TestDuplexStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TestDuplexStream = channel.stream_stream(
                '/test.TestDuplex/TestDuplexStream',
                request_serializer=data__pb2.TestDuplexStreamRequest.SerializeToString,
                response_deserializer=data__pb2.TestDuplexStreamResponse.FromString,
                )


class TestDuplexServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TestDuplexStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TestDuplexServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TestDuplexStream': grpc.stream_stream_rpc_method_handler(
                    servicer.TestDuplexStream,
                    request_deserializer=data__pb2.TestDuplexStreamRequest.FromString,
                    response_serializer=data__pb2.TestDuplexStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'test.TestDuplex', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TestDuplex(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TestDuplexStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/test.TestDuplex/TestDuplexStream',
            data__pb2.TestDuplexStreamRequest.SerializeToString,
            data__pb2.TestDuplexStreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
